// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjekat.Data;

namespace WebProjekat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200829192931_AddedDateOfReservToFlightOfRes")]
    partial class AddedDateOfReservToFlightOfRes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProjekat.Models.AirplaneCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AirplaneCompanies");
                });

            modelBuilder.Entity("WebProjekat.Models.BonusInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlightBonus")
                        .HasColumnType("int");

                    b.Property<int>("RentacarBonus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BonusInfo");
                });

            modelBuilder.Entity("WebProjekat.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropoffLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("WebProjekat.Models.CarReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("DropoffDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("CarReservations");
                });

            modelBuilder.Entity("WebProjekat.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DateOfLanding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfTakingOff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistanceOfFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationOfFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationOfTransfers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfTransfers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceOfTicketOfFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfLanding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfTakingOff")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("WebProjekat.Models.FlightReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AirplaneCompanyOfReservationId")
                        .HasColumnType("int");

                    b.Property<string>("CityOfUserWhoSits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfReservation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstNameOfPersonWhoSits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightOfReservationId")
                        .HasColumnType("int");

                    b.Property<string>("NumberOfPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneOfUserWhoSits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceOfReservation")
                        .HasColumnType("int");

                    b.Property<int>("SeatOfReservation")
                        .HasColumnType("int");

                    b.Property<string>("SecondNameOfPersonWhoSits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfReservation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserWhoReservedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneCompanyOfReservationId");

                    b.HasIndex("FlightOfReservationId");

                    b.HasIndex("UserWhoReservedId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("WebProjekat.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComapnyId")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComapnyId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WebProjekat.Models.RentacarBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("RentacarBranches");
                });

            modelBuilder.Entity("WebProjekat.Models.RentacarCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("RentacarCompanies");
                });

            modelBuilder.Entity("WebProjekat.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityOfNonUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoesItExist")
                        .HasColumnType("bit");

                    b.Property<string>("FirstNameOfUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightBelongingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsItAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItReserved")
                        .HasColumnType("bit");

                    b.Property<string>("LastNameOfUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeat")
                        .HasColumnType("int");

                    b.Property<string>("PhoneOfNonUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WhoCreatedItId")
                        .HasColumnType("int");

                    b.Property<int?>("WhoReservedItId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightBelongingId");

                    b.HasIndex("WhoCreatedItId");

                    b.HasIndex("WhoReservedItId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("WebProjekat.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BonusPoints")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompanyAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PasswordChanged")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebProjekat.Models.AirplaneCompany", b =>
                {
                    b.HasOne("WebProjekat.Models.User", "Admin")
                        .WithMany("AirlineCompanies")
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("WebProjekat.Models.Car", b =>
                {
                    b.HasOne("WebProjekat.Models.RentacarBranch", "Branch")
                        .WithMany("Cars")
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("WebProjekat.Models.CarReservation", b =>
                {
                    b.HasOne("WebProjekat.Models.Car", "Car")
                        .WithMany("CarReservations")
                        .HasForeignKey("CarId");

                    b.HasOne("WebProjekat.Models.User", "User")
                        .WithMany("CarReservations")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("WebProjekat.Models.Flight", b =>
                {
                    b.HasOne("WebProjekat.Models.AirplaneCompany", "Company")
                        .WithMany("Flights")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("WebProjekat.Models.FlightReservation", b =>
                {
                    b.HasOne("WebProjekat.Models.AirplaneCompany", "AirplaneCompanyOfReservation")
                        .WithMany()
                        .HasForeignKey("AirplaneCompanyOfReservationId");

                    b.HasOne("WebProjekat.Models.Flight", "FlightOfReservation")
                        .WithMany()
                        .HasForeignKey("FlightOfReservationId");

                    b.HasOne("WebProjekat.Models.User", "UserWhoReserved")
                        .WithMany()
                        .HasForeignKey("UserWhoReservedId");
                });

            modelBuilder.Entity("WebProjekat.Models.Location", b =>
                {
                    b.HasOne("WebProjekat.Models.AirplaneCompany", "Comapny")
                        .WithMany("Destinations")
                        .HasForeignKey("ComapnyId");
                });

            modelBuilder.Entity("WebProjekat.Models.RentacarBranch", b =>
                {
                    b.HasOne("WebProjekat.Models.RentacarCompany", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("WebProjekat.Models.RentacarCompany", b =>
                {
                    b.HasOne("WebProjekat.Models.User", "Admin")
                        .WithMany("RentacarCompany")
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("WebProjekat.Models.Seat", b =>
                {
                    b.HasOne("WebProjekat.Models.Flight", "FlightBelonging")
                        .WithMany("Seats")
                        .HasForeignKey("FlightBelongingId");

                    b.HasOne("WebProjekat.Models.AirplaneCompany", "WhoCreatedIt")
                        .WithMany()
                        .HasForeignKey("WhoCreatedItId");

                    b.HasOne("WebProjekat.Models.User", "WhoReservedIt")
                        .WithMany()
                        .HasForeignKey("WhoReservedItId");
                });
#pragma warning restore 612, 618
        }
    }
}
